services:
  backend:
    build:
      context: ./dropwizard-backend
    ports:
      - "8080:8080"
    expose:
      - "8080"

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
