services:
  backend:
    build: ./dropwizard-backend
    ports:
      - "8080:8080"
    working_dir: /app
    container_name: coinminner-backend

  frontend:
    build: ./react-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    container_name: coinminner-frontend
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
